name: Docker Build and Push

on:
  push:
    branches: [actions]

jobs:
  middleman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo -n $DOCKER_PASSWORD | docker login --username cschiewek --password-stdin
      - name: Build
        env:
          IMAGE: middleman
        run: make build
      - name: Push
        env:
          IMAGE: middleman
        run: make push
      - name: Notify
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Actions
          SLACK_CHANNEL: app-log-csk
          SLACK_OVERRIDE_MESSAGE: true
        with:
          args: 'A new version of the csk-middleman docker image has been built and pushed.'
