name: Docker Build and Push

on:
  push:
    branches: [master]

jobs:
  middleman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/docker/login
        secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
      - name: Build and Push
        env:
          IMAGE: middleman
        run: make build
