name: Docker Build and Push

on:
  push:
    branches: [master]

jobs:
  middleman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        env:
          IMAGE: middleman
        run: make build
      - name: Notify
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Github Actions
          SLACK_CHANNEL: app-log-csk
        with:
          args: 'A new version of the csk-middleman docker image has been built and pushed.'
