name: Docker Build and Push

on:
  push:
    branches: [master]

jobs:
  middleman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        env:
          IMAGE: middleman
        run: make build
