name: Docker Build and Push

on:
  push:
    branches: [actions]

jobs:
  middleman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: cschiewek
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login
        run: docker login
      - name: Info
        run: docker info
