name: Docker Build and Push

on:
  push:
    branches: [actions]

jobs:
  middleman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo -n $DOCKER_PASSWORD | docker login --username cschiewek --password-stdin
      - name: Check
        run: cat $HOME/.docker/config.json
